services:
  - type: web
    name: excellence-tutorial-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn -k eventlet --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SECRET_KEY
        generateValue: true

  - type: postgres
    name: excellence-tutorial-db
    plan: free

  # Optional: Daily scheduler for more frequent checks
  # Uncomment the section below if you want daily checks
  # - type: cron
  #   name: daily-scheduler
  #   env: python
  #   schedule: "0 6 * * *"  # Run at 6 AM daily (IST)
  #   buildCommand: |
  #     pip install -r requirements.txt
  #   startCommand: "python scripts/scheduler.py"
  #   envVars:
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: excellence-tutorial-db
  #         property: connectionString
  #     - key: FLASK_ENV
  #       value: production 